apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fraud-detection-api
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fraud-detection-api.10.232.255.254.sslip.io`)
      kind: Rule
      services:
        - name: fraud-detection-api
          port: 80
    - match: Host(`fraud-detection-api.127.0.0.1.sslip.io`)
      kind: Rule
      services:
        - name: fraud-detection-api
          port: 80