[project]
name = "fraud-detection-platform"
version = "1.0.0"
requires-python = "==3.12.13"

[dependency-groups]
lint = [
    "ruff>=0.16.5",
]
stubs = [
    "boto3-stubs[mwaa,s3]>=1.43.83",
    "matplotlib-stubs>=0.3.11",
    "pandas-stubs>=3.0.5.260730",
    "pyarrow-stubs>=20.0.0.20260819",
    "types-seaborn>=0.13.2.20260728",
]
type_check = [
    "mypy>=2.3.1",
]

[tool.uv]
required-version = "0.12.6"
default-groups = ["lint", "stubs", "type-check"]
workspace.members = [
    "notebooks",
    "services",
    "services/dags_images",
    "tools/dags",
    "tools",
]