# Directories
OPERATIONS_DIRECTORY 			 := $(MAKEFILE_DIRECTORY)/operations
OPERATIONS_MAIN_DIRECTORY 		 := $(OPERATIONS_DIRECTORY)/main
OPERATIONS_MAIN_SCRIPT_DIRECTORY := $(OPERATIONS_MAIN_DIRECTORY)/scripts