# Script Runner
define RUN_INFRASTRUCTURE_SCRIPT
$(call RUN_BASH_SCRIPT,$(INFRASTRUCTURE_SCRIPT_DIRECTORY),$(1))
endef
# Docker
define RUN_INFRASTRUCTURE_TARGET_IN_CONTAINER
$(call RUN_TARGET_IN_CONTAINER,$(INFRASTRUCTURE_CONTAINER_SCRIPT_DIRECTORY),$(INFRASTRUCTURE_IMAGE),$(INFRASTRUCTURE_CONTAINER),$(1))
endef