apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-api
  labels:
    app: fraud-detection-api
spec:
  selector:
    app: fraud-detection-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP