name: Setup Atlas Community
description: Setup Atlas Community Edition (Apache 2.0), official can't get the community version.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euo pipefail

        ATLAS_DIRECTORY="${RUNNER_TEMP}/atlas"
        mkdir --parents "${ATLAS_DIRECTORY}"
        
        ATLAS_INSTALLER="${ATLAS_DIRECTORY}/atlasgo.sh"
        curl --silent --fail --location --output "${ATLAS_INSTALLER}" "https://atlasgo.sh"
        
        CI=true ATLAS_VERSION=v1.2.0 sh "${ATLAS_INSTALLER}" --community