name: AWS Secrets Manager Upsert Secrets
description: Loops over a JSON to upsert secrets.
inputs:
  config:
    required: true
    description: JSON pairs of secrets to upsert.
runs:
  using: composite
  steps:
    - shell: bash
      env:
        CONFIG: ${{ inputs.config }}
      run: |
        set -euo pipefail

        printf "%s" "${CONFIG}" | jq empty

        temporary_file=$(mktemp --tmpdir="${RUNNER_TEMP}")
        chmod 600 "${temporary_file}"
        trap 'rm --force "${temporary_file}"' EXIT

        while IFS= read -r -d '' key && IFS= read -r -d '' value; do

          printf "%s" "${value}" > "${temporary_file}"

          if aws secretsmanager describe-secret --secret-id "${key}" &>/dev/null; then
            aws secretsmanager put-secret-value \
              --secret-id "${key}" \
              --secret-string "file://${temporary_file}"
          else
            aws secretsmanager create-secret \
              --name "${key}" \
              --secret-string "file://${temporary_file}"
          fi
        done < <(
          printf "%s" "${CONFIG}" |
            jq --join-output '
              to_entries[] |
              .key,
              "\u0000",
              (.value | if type == "string" then . else tojson end),
              "\u0000"
            '
        )