# ci/image-filter
archive:
  - services/dags_images/archive/**
  - services/shared/**
  - services/pyproject.toml
  - services/uv.lock

drift-check:
  - services/dags_images/drift_check/**
  - services/shared/**
  - services/pyproject.toml
  - services/uv.lock

train-model:
  - services/dags_images/train_model/**
  - services/shared/**
  - services/pyproject.toml
  - services/uv.lock