# Script Runner
define RUN_START_PIPELINE_SCRIPT
$(call RUN_BASH_SCRIPT,$(START_PIPELINE_SCRIPT_DIRECTORY),$(1))
endef
# Docker
define RUN_START_PIPELINE_TARGET_IN_CONTAINER
$(call RUN_TARGET_IN_CONTAINER,$(MAIN_SCRIPT_DIRECTORY),$(START_PIPELINE_IMAGE),$(START_PIPELINE_CONTAINER),$(1))
endef