name: Test / Docker

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t test-archive:${{ github.sha }} -f services/dags/archive/Dockerfile --target test-dev . -q
          echo "Built image: test-archive:${{ github.sha }}"

      - name: Run image
        run: docker run --rm test-archive:${{ github.sha }}