name: CI

on:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Allow dorny/paths-filter to get the whole history in nektos/act

      # Set dorny/paths-filter base to first commit to always proceed to succeeding jobs in nektos/act
      - name: Get initial commit
        id: initial-commit
        run: echo "sha=$(git rev-list --max-parents=0 HEAD)" >> ${GITHUB_OUTPUT}

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            services:
              - 'services/**'
          base: ${{ steps.initial-commit.outputs.sha }}# Set dorny/paths-filter base to first commit to always proceed to succeeding jobs in nektos/act

  build:
    needs: changes
    if: needs.changes.outputs.services == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: echo "Changes detected in services/**"