[project]
name = "dags_images"
version = "1.0.0"
requires-python = "==3.12.13"

[dependency-groups]
# Tasks
archive = [
    "pandas>=2.3.3",
    "pyarrow>=25.0.1",
    { include-group = "shared" },
]
drift_check = [
    "evidently>=0.7.21",
    "pandas>=2.3.3",
    "pyarrow>=25.0.1",
    { include-group = "shared" },
]
train_model = [
    "imbalanced-learn>=0.14.2",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "optuna>=4.9.0",
    "pandas>=2.3.3",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
    "xgboost>=3.4.1",
    { include-group = "shared" },
]
# Tests
test_archive = [
    { include-group = "archive" },
    { include-group = "test" },
]
test_drift_check = [
    { include-group = "drift_check" },
    { include-group = "test" },
]
test_train_model = [
    { include-group = "train_model" },
    { include-group = "test" },
]
# Base
shared = [
    "boto3>=1.43.83",
    "mlflow-skinny>=3.15.2",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    # sqlalchemy dependendencies
    "psycopg2-binary>=2.9.12",
    # mlflow-skinny dependencies
    "alembic>=1.19.1",
]
test = [
    "pyfakefs>=6.2.0",
    "pytest>=9.1.1",
    "pytest-env>=1.7.0",
    "pytest-mock>=3.15.1",
]

[tool.uv]
required-version = "0.12.6"

[tool.pytest.ini_options]
python_files = ["[a-z]*.py"]
env = [
    # services/dags_images/archive/modules/environment/archive.py
    "TRANSACTION_INFERENCES_ISO_DATETIME_CUTOFF=0001-01-01T00:00:00+00:00",
    # services/dags_images/drift_check/modules/environment/drift_check.py
    "ACTIVE_MODEL_DEPLOYMENT_MLFLOW_RUN_ID=active-mlflow-run-default",
    # services/shared/modules/environment/mlflow.py
    "MLFLOW_TRACKING_URI=http://localhost:0000",
    "MLFLOW_TRACKING_USERNAME=mlflow-username-default",
    "MLFLOW_TRACKING_PASSWORD=mlflow-password-default",
    "MLFLOW_WORKSPACE=mlflow-workspace-default",
    # services/shared/modules/environment/mwaa.py
    "AWS_DEFAULT_REGION=aws-region-default",
    "AWS_ENDPOINT_URL_MWAA=http://localhost:0000",
    "AWS_ACCESS_KEY_ID=aws-access-default",
    "AWS_SECRET_ACCESS_KEY=aws-secret-default",
    "MWAA_ENVIRONMENT_NAME=mwaa-environment-default",
    # services/shared/modules/environment/postgres.py
    "PGHOST=postgres-host-default",
    "PGPORT=0000",
    "PGDATABASE=postgres-database-default",
    "PGUSER=postgres-user-default",
    "PGPASSWORD=postgres-password-default",
    # services/shared/modules/environment/s3.py
    "AWS_DEFAULT_REGION=aws-region-default",
    "AWS_ENDPOINT_URL_MWAA=http://localhost:0000",
    "AWS_ACCESS_KEY_ID=aws-access-default",
    "AWS_SECRET_ACCESS_KEY=aws-secret-default",
    "S3_BUCKET_NAME=s3-bucket-default",
    # services/shared/modules/environment/slack.py
    "SLACK_APP_LEVEL_TOKEN=slack-app-token-default",
    "SLACK_BOT_USER_OAUTH_TOKEN=slack-bot-token-default",
    "SLACK_CHANNEL_ID=C000000000",
    "SLACK_SIGNING_SECRET=slack-signing-secret-default",
]