# TODO - 12/09/2026 - Continue here... Build CI/CD
name: CD / Fraud Detection API

on:
  push:
    branches: [main]
    paths:
      - services/fraud_detection_api/**
      - services/shared/**
      - pyproject.toml
      - uv.lock
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
  # noinspection YAMLSchemaValidation
  queue: max

env:
  AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }} # MiniStack URL
  IMAGE_NAME: fraud-detection-api

jobs:
  push:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-buildx-action@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          # sts-endpoint: ${{ secrets.AWS_ENDPOINT_URL }} # TODO Check if global env is enough

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tags & labels
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ steps.ecr-login.outputs.registry }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=sha-,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & push
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          target: runtime
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          provenance: mode=max

  deploy:
    needs: [push]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Deploy
        env:
          IMAGE_REF: ${{ needs.push.outputs.registry }}/${{ env.IMAGE_NAME }}@${{ needs.push.outputs.digest }}
        run: |
          echo "Deploying $IMAGE_REF"
          # kubectl set image deployment/fraud-detection-api app=$IMAGE_REF