name: CD / Migrate

on:
  push:
    branches: [main]
    paths:
      - database/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get database URL
        uses: aws-actions/aws-secretsmanager-get-secrets@v3
        with:
          secret-ids: DATABASE_URL, ${{ secrets.SECRET_PATH }}/postgres/migration-database-url

      - uses: ./.github/actions/setup-atlas-community
      - name: Apply migrations
        working-directory: database
        env:
          URL: ${{ env.DATABASE_URL }}
        run: atlas migrate apply --env production