name: CI / DAGs

on:
  pull_request:
    branches: [main]
    paths:
      - dags/**
      - tests/dags/**
      - services/dags_images/**
      - tests/services/dags_images/**
      - services/shared/**
      - tests/services/shared/**
      - pyproject.toml
      - uv.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      images-changes: ${{ steps.image-filter.outputs.changes }}
      dags-changed: ${{ steps.dags-filter.outputs.dags }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Allow dorny/paths-filter to get the whole history in nektos/act

      # Set dorny/paths-filter base to first commit to always proceed to succeeding jobs in nektos/act
      - name: Get initial commit
        id: initial-commit
        run: echo "sha=$(git rev-list --max-parents=0 HEAD)" >> ${GITHUB_OUTPUT}

      - uses: dorny/paths-filter@v4
        id: image-filter
        with:
          filters: .github/config/paths-filter/dags/ci/image-filter.yaml
          base: ${{ steps.initial-commit.outputs.sha }} # Set dorny/paths-filter base to first commit to always proceed to succeeding jobs in nektos/act
          token: '' # Allow dorny/paths-filter to use base on pull request event in nektos/act

      - uses: dorny/paths-filter@v4
        id: dags-filter
        with:
          filters: .github/config/paths-filter/dags/ci/dags-filter.yaml
          base: ${{ steps.initial-commit.outputs.sha }} # Set dorny/paths-filter base to first commit to always proceed to succeeding jobs in nektos/act
          token: '' # Allow dorny/paths-filter to use base on pull request event in nektos/act

  test-images:
    needs: detect-changes
    if: needs.detect-changes.outputs.images-changes != '[]'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJson(needs.detect-changes.outputs.images-changes) }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-buildx-action

      - name: Resolve Dockerfile path
        id: dockerfile-path
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          FOLDER="${IMAGE//-/_}"
          echo "path=services/dags_images/${FOLDER}/Dockerfile" >> $GITHUB_OUTPUT

      - name: Test
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ steps.dockerfile-path.outputs.path }}
          target: test
          push: false
          cache-from: type=gha,scope=${{ matrix.image }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image }}

  test-dags:
    needs: detect-changes
    if: needs.detect-changes.outputs.dags-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-buildx-action

      - name: Test
        uses: docker/build-push-action@v7
        with:
          context: .
          file: tests/dags/Dockerfile
          target: test
          push: false
          cache-from: type=gha,scope=dags
          cache-to: type=gha,mode=max,scope=dags